### ISSUE TITLE
ES6 Modules Not Supported(?)

### ISSUE THREAD

**Issue by pahund** [wallabyjs/wallaby-es6-sample#1]
Hi Artem,

the example works fine on my machine (IntelliJ IDEA Ultimate v14.1.1 / Wallaby v1.0.7).

However, it seems to not work with ES6 modules.
You can easily try this out by adding this line:
`export default Calculator;`
to [calculator.js](https://github.com/wallabyjs/wallaby-es6-sample/blob/master/src/calculator.js).

My Wallaby console complains: "Runtime error: ReferenceError: Can't find variable: module"

Is this a bug, or missing feature, or am I doing it wrong?

Cheers, Patrick

**Comment by ArtemGovorov** [comment]
Hi Patrick,

ES6 modules are supported by wallaby (and Babel). What actually happens is that generated code looks like:

``` javascript
module.exports = Calculator;
```

That's how Babel [transpiles by default](https://babeljs.io/docs/usage/modules/) - to CommonJs. Wallaby.js by default runs tests for browser (using PhantomJs) and browser environment has no idea about what `module` is, hence the error.

In order to make it work you may add  `env` setting to [make your tests run in node.js](https://github.com/wallabyjs/public#environment-setting) (that supports CommonJs)

```
module.exports = function () {
  return {
    files: [
      'src/*.js'
    ],

    tests: [
      'test/*Spec.js'
    ],

    preprocessors: {
      '**/*.js': file => require('babel').transform(file.content, {sourceMap: true})
    },

    env: {
      type: 'node'
    }
  };
};
```

(it will start showing another error in spec that it can't find Calculator, all you need to to is `import` it using ES6 imports).

Note that in this case you'll be using node.js as your testing environment (so won't have an access to browser environment, like window, DOM, etc.). 

While some people prefer this way of testing browser code (with something like [jsdom](https://github.com/tmpvar/jsdom)), if you're intending to write your code and tests for browser using ES6 modules and would like to run your tests in browser environment, then you have a few options:
- keep Babel transpiling your code to CommonJs and to use something like Browserify or Webpack to build your code. These module bundlers take CommonJs code and 'build' it for browser. Wallaby support both, have a look into [this sample repo](https://github.com/wallabyjs/wallaby-webpack-sample), it uses ES6 modules with webpack in browser tests. Browserify [sample is here](https://github.com/wallabyjs/wallaby-browserify-sample), it's not using ES6, but can be configured the similar way as Webpack.
- configure Babel (by providing options in the preprocessor configuration line of code) to use a different [module output format](https://babeljs.io/docs/usage/modules/), such as AMD and then use for example require.js, that is also [supported by wallaby.js](https://github.com/wallabyjs/wallaby-requirejs-sample).

P.S. If you'd like see the modified code that wallaby runs (after Babel and wallaby modifications), you may add `debug: true` property to the root config object in wallaby config and it wallaby console one of the first things it outputs is a wallaby cache folder. Have a look into `instrumented` folder to see how exactly the code that wallaby executes looks like.

**Comment by pahund** [comment]
Ah, I see. I actually do use webpack for my project, so I'll try out the other sample. Thanks!

**Comment by ArtemGovorov** [comment]
Cool, let me know if that sample doesn't work for you.
BTW, if you'd like to use some latest ES7 features supported by Babel, you may also consider configuring it as a [compiler](https://github.com/wallabyjs/public#compilers-setting) as opposed to preprocessor. There's a [basic sample](https://github.com/wallabyjs/wallaby-babel-es7-sample/) for such configuration and there's also one where it's [configured with Webpack](https://github.com/wallabyjs/wallaby-webpack-es7) (please note that in the latter one there are some failing tests and that's expected).
